services:
  - type: web
    name: support-bot
    env: python
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y wkhtmltopdf python3-imgkit
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python bot.py
